### ISSUE TITLE
Plugin responsivity with another Quests plugin

### ISSUE THREAD

**Issue by Rikkiko** [LMBishop/Quests#502] opened 2023-03-14 22:17 UTC
### Description of Feature

We used the Quests plugin and the community loved so much, and they want it back. So the problem is that we just started to use another Quests plugin too and **the plugin names, commands are the same.** So sadly we cant use both. Is there any chance that the developers make it responsive for work them both? 

### Reason for Addition

To make the two Quests plugins work well at the same time.

### Alternative Solutions

 If the first is impossible, Is there any chance that the developers change the plugin name and commands for us and send it to me? Like this: from Quests to QuestGUI and from the commands from Quests to QuestsGUI, alliases: from q to qGUI / guest to questGUI ? we tried to change the BukkitQuestsPlugin.class but didnt work well 😦 I would really appreciate it if possible to make it.

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this request is unique and a similar issue is not currently open

**Comment by Krakenied** [comment] 2023-03-14 22:40
Duplicate of #465

**Closed** 2023-08-07 17:50 UTC
Labels: resolution: duplicate, enhancement
