### ISSUE TITLE
Shopgui And Quests Bug

### ISSUE THREAD

**Issue by spartan090907** [LMBishop/Quests#435] opened 2022-08-04 12:49 UTC
### Description of Bug

If many people buy from shop at same time it lags a little

[04.08 12:47:12] [Server] [ERROR] Could not pass event ShopPostTransactionEvent to Quests v3.13.1-77ab390
[04.08 12:47:12] [Server] java.lang.NoSuchMethodError'net.brcdev.shopgui.shop.ShopItem net.brcdev.shopgui.shop.ShopTransactionResult.getShopItem()'
[04.08 12:47:12] [Server] 	at com.leonardobishop.quests.bukkit.tasktype.type.dependent.ShopGUIPlusBuyTaskType.afterTransaction(ShopGUIPlusBuyTaskType.java:49) ~[Quests-3.13.1-77ab390.jar:?]
[04.08 12:47:12] [Server] 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1037.execute(Unknown Source) ~[?:?]
[04.08 12:47:12] [Server] 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:?]
[04.08 12:47:12] [Server] 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:git-Purpur-1748]
[04.08 12:47:12] [Server] 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:?]
[04.08 12:47:12] [Server] 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:?]
[04.08 12:47:12] [Server] 	at net.brcdev.shopgui.shop.ShopManager.handleItemBuy(ShopManager.java:971) ~[ShopGUIPlus-1.78.0.jar:?]
[04.08 12:47:12] [Server] 	at net.brcdev.shopgui.listener.PlayerListener.clickAmountSelectionGui(PlayerListener.java:403) ~[ShopGUIPlus-1.78.0.jar:?]
[04.08 12:47:12] [Server] 	at net.brcdev.shopgui.listener.PlayerListener.onInventoryClick(PlayerListener.java:141) ~[ShopGUIPlus-1.78.0.jar:?]
[04.08 12:47:12] [Server] 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor441.execute(Unknown Source) ~[?:?]
[04.08 12:47:12] [Server] 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:?]
[04.08 12:47:12] [Server] 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:git-Purpur-1748]
[04.08 12:47:12] [Server] 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:?]
[04.08 12:47:12] [Server] 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:?]
[04.08 12:47:12] [Server] 	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3380) ~[?:?]
[04.08 12:47:12] [Server] 	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
[04.08 12:47:12] [Server] 	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
[04.08 12:47:12] [Server] 	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
[04.08 12:47:12] [Server] 	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.1.jar:git-Purpur-1748]
[04.08 12:47:12] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
[04.08 12:47:12] [Server] 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
[04.08 12:47:12] [Server] 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1386) ~[purpur-1.19.1.jar:git-Purpur-1748]
[04.08 12:47:12] [Server] 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.1.jar:git-Purpur-1748]
[04.08 12:47:12] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
[04.08 12:47:12] [Server] 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1363) ~[purpur-1.19.1.jar:git-Purpur-1748]
[04.08 12:47:12] [Server] 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1356) ~[purpur-1.19.1.jar:git-Purpur-1748]
[04.08 12:47:12] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
[04.08 12:47:12] [Server] 	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1334) ~[purpur-1.19.1.jar:git-Purpur-1748]
[04.08 12:47:12] [Server] 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1222) ~[purpur-1.19.1.jar:git-Purpur-1748]
[04.08 12:47:12] [Server] 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.1.jar:git-Purpur-1748]
[04.08 12:47:12] [Server] 	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Steps to Reproduce

Have quests and shopgui+ on a server. buy something from shopgui and it will send the message

### Environment

- Minecraft version: 1.19.1
- Server software: Purpur-1748
- Quests version: 3.13.1

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by AlternativeSoap** [comment] 2022-08-05 22:13
So annoying! Was coming here to report this, but I saw this!

**Comment by LMBishop** [comment] 2022-08-06 00:56
Duplicate of #429

**Closed by LMBishop** 2022-08-06 00:56 UTC
Labels: bug, resolution: duplicate
