### ISSUE TITLE
Error when starting on a 1.21 server

### ISSUE THREAD

**Issue by DextralityEarth** [LMBishop/Quests#698] opened 2024-07-29 02:11 UTC
### Description of Bug

When I changed from 1.20.4 to 1.21 all the plugins I have been updating including the Quests one, and I got this error

### Steps to Reproduce

- Start the server
- Use the latest version of 1.21

### Environment

- Minecraft version:
- Server software:
- Quests version:

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

### Other

Error: https://paste.helpch.at/lonedukova.php

Full server log: https://paste.helpch.at/murizugapu.makefile

**Comment by Krakenied** [comment] 2024-07-29 13:23
Duplicate of https://github.com/LMBishop/Quests/issues/697. Latest build can be download here https://cdn.discordapp.com/attachments/510553623022010371/1266900604522074162/Quests-3.15-b2a7391.jar?ex=66a8cee1&is=66a77d61&hm=f9b110d151bc0df50689e37f461ba90c5b461ea45576c5b291cb215b495a2757&

**Closed** 2024-08-28 09:37 UTC
Labels: bug, status: needs investigating
