### ISSUE TITLE
fishingcertain doesnt work

### ISSUE THREAD

**Issue by blank826** [LMBishop/Quests#194] opened 2021-06-28 06:49 UTC
### Description of Bug

tasks:
  fishingcertain:
    type: "fishingcertain"
    item: RAW_FISH
    amount: 2
    data: 3
    worlds:
     - "world"
This is my task.I want to get 2 pufferfish.But when i catch two Raw Salmon also can complete this task.

### Steps to Reproduce

 when i catch two Raw Salmon also can complete this task.

### Environment

- Minecraft version: Paper 1.12.2
- Server software: 
- Quests version: 3.1.4

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by LMBishop** [comment] 2021-06-28 09:34
Duplicate of #191 (you can reopen them)

**Closed by LMBishop** 2021-06-28 09:34 UTC
Labels: bug, resolution: duplicate

**Comment by blank826** [comment] 2021-06-28 09:37
Hi,i know you means.But when you add data also dont work.I have already test from my server.

**Comment by blank826** [comment] 2021-06-28 09:39
You can test it use my send the task.I did not send malicious BUG.Paper 1.12.2
